//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLearningDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource
    {
        public string id { get; set; }
        public System.DateTimeOffset C__createdAt { get; set; }
        public System.DateTimeOffset C__updatedAt { get; set; }
        public byte[] C__version { get; set; }
        public bool C__deleted { get; set; }
        public string LocalPath { get; set; }
        public string CloudPath { get; set; }
        public string ContainerName { get; set; }
        public string SasQueryString { get; set; }
    }
}
